FROM bitnami/spark:latest

USER root
RUN install_packages python3 python3-distutils python3-venv python3-pip
RUN pip3 install --break-system-packages requests psycopg2-binary
RUN /usr/bin/python3 -m pip install requests psycopg2-binary --break-system-packages
ENV PYSPARK_PYTHON=/usr/bin/python3
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
USER 1001
