FROM bitnami/spark:latest

USER root

# Cài python3 (Debian base)
RUN install_packages python3 python3-distutils python3-venv python3-pip

ENV PYSPARK_PYTHON=/usr/bin/python3
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3

RUN pip3 install minio

USER 1001
